# Generated by Django 4.0 on 2023-08-13 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_averge_starts_alter_start_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='averge_starts',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
