# Generated by Django 4.0 on 2023-08-13 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_averge_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='star',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
